# Default values for klusterlet.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

ClusterName: cluster4
Hub:
  APIServer: https://hub-control-plane:6443
  KubeConfig: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeE1Ea3lNVEF4TURJd04xb1hEVE14TURreE9UQXhNREl3TjFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTEwvClZLeWc5S3B0dm05dlMrcTJZU2JIVnVWVEZ6VW9icllGMmlva2VrL0tOWk9EQmhwMjlkd0ZUS2ZibkxNSlc2Q0MKV1R3N0VvWDd4dklrZXcvTTBaWUVaa0U4aXo1WE5aS0lqMWpVMHU4MVZIaEFmY201d3E2bERhWFlML3V1MjRWVgpBaVVqRWRCNlZ1YnVwYzJhQ1A0OGJqYTdNWU94OTlTWDV1aVcwL1ZVaFdzQURtM0F6OWRLd2lweDBGTm81T2ZKCmVGaG53NHBXYWRscmdxd0NFdjJmOExRWlB0ay9pQ1NQUzNxbTk2bDNSa0pqQk5Kbk15NVhIUFM5TWl6Y1pENUMKRk9mUENDM0wrYUF3WWxvNVhLeGRvWXBGME5XVUs4UmRSTnlYdE91TmdMUnk4TG9RRVdScnVPR3VTN3g4UnJ4YgoyU2lkZmNaWi9Ka0VtZlVleXA4Q0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZJd1AzRjlqNVljYmV1MlpkcmtqVlgrSDgwTjJNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFDUm45K3ZBcHBVcUhha3VMdjdsU2V2UWREUzgxNFVKZDJmd1VPZTRmdzlneXlzL3lCZgpJQ2hvOENkQlZXTnRYYTZxQ1ZERjhLa1RIQ0R2RzZjRnhWU2N4Uk9ObUVlbGxIOXlubXc0alZwWTFNRGo4Sm1UClNoWlk3QTVnZG9sajZTdEFjdDRhTjZJWDhEUjhGaVIvZkZ4aTJTazhzOTdZM1hvcFNMY0FqQkxpQ0FJa1NXYisKT1lYOG5NLzIrM1laTWtWZzdSSDNrcVpsOGVIK09oRUlqK3pPQUx1c3NqMTFpR05jMGhNRlkrRC9DNTc0RmpxaApIQmtMQ2EzVjJ5VUxrQlpoa1dnUi8wbjVKRjRSc1gxZlZNb0ptTGFFN3pOeWR4M3dlYUkzWEZoclpmMXBQWHdmCkQvMzRZTnNubHNRVURUWHpLYnNja3lCOXpPeStCMW9BOHJZQQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        server: https://hub-control-plane:6443
      name: kind-hub
    contexts:
    - context:
        cluster: kind-hub
        user: kind-hub
      name: kind-hub
    current-context: kind-hub
    kind: Config
    preferences: {}
    users:
    - name: kind-hub
      user:
        token: eyJhbGciOiJSUzI1NiIsImtpZCI6IlpuZkswRE53am93R0pTSjB0d2RPMWM3cHBLZW9LckFzbkxMRVBXRkpHWjAifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJvcGVuLWNsdXN0ZXItbWFuYWdlbWVudCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJjbHVzdGVyLWJvb3RzdHJhcC10b2tlbi16cmZsNCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJjbHVzdGVyLWJvb3RzdHJhcCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImRjODM1ZjUwLWI5MWMtNDc0Mi05MGM0LTVmNjRhZTJkY2QwZiIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpvcGVuLWNsdXN0ZXItbWFuYWdlbWVudDpjbHVzdGVyLWJvb3RzdHJhcCJ9.aPnZ2Jo0Jo_vzEgcxRBsDLOZcVT6qm16EPXVirluRn1aMfiK5s0SsrRkSNrqI3E0VtoLMMEPodRd4yCwJgPw2epK_R1vYLXRPOAYhh8AzWqNzdt-LRcq89raY7-j3fZF3eQR72iu_VZajQF9EfG5d8lGNCBOgERhZCZh4BzcBt3FMcOsUJjm9iuGXthcoLNvsUmcC5s4u0c5lXfwz4KYm5kGD8MrY0vcsM19DWUES-saJKx1dJnGq88_gK9jQSrzNWvXNclI3k86YJn5t5Cb-3URenebogfLhpPawnu8YmTO5n_z11rDjoTebxXDhIP_Aq2_fis0A9XyZapsMJvYzg


 